blacksmith:
  image: leanlabs/blacksmith
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    - REDIS_ADDR=redis:6379
    - GITHUB_CLIENT_ID=qwerty
    - GITHUB_CLIENT_SECRET=qwerty
    - BS_SERVER_HOSTNAME=http://blacksmith.com
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - redis:redis
  ports:
    - 80:80
  command: daemon

redis:
  image: leanlabs/redis
